### ISSUE TITLE
IapManager doesn't work

### ISSUE THREAD

**Issue by ManuelRuiz2504** [EvilMindDevs/hms-unity-plugin#10]
Hello,

Thanks for your work, it is very useful.
I have some problems with IapManager. I'm going to explain it.
In the Readme, it said that you can call BuyProduct method just with an argument, a string. Also, in the demo, it called that method with a string (I know that demos are WIP).

<img width="630" alt="Captura de pantalla 2020-05-20 a las 9 28 31" src="https://user-images.githubusercontent.com/50315633/82419367-9683d380-9a7e-11ea-99c4-33441404306d.png">

But when I try to call it from my script, it shows an error:

<img width="1098" alt="Captura de pantalla 2020-05-20 a las 9 29 37" src="https://user-images.githubusercontent.com/50315633/82419470-c337eb00-9a7e-11ea-964b-250c9049eba3.png">

This is because in IapManager.cs, the method BuyProduct has the argument of type ProductInfo (this has been downloaded from your repository):

<img width="482" alt="Captura de pantalla 2020-05-20 a las 9 28 43" src="https://user-images.githubusercontent.com/50315633/82419589-ecf11200-9a7e-11ea-9699-a08a5ee5ceea.png">

I don't know if this is a recently change or just a mistake. I would like to know if you are thinking in fix it and to use again an string because it is more easy to configure.

Furthermore, when I try to assign the method by UI, it doesn't appear, even been a public method.

<img width="729" alt="Captura de pantalla 2020-05-20 a las 9 29 00" src="https://user-images.githubusercontent.com/50315633/82419874-435e5080-9a7f-11ea-99d4-af4d8cbaa1da.png">

Please, let me know if you knew about that problems and if you are thinking in fix them.
Again, thank you so much for your work.

**Comment by m0skit0** [comment]
Hi Manuel

Thanks a lot for your feedback. This was changed to make it more flexible because sometimes you might want more information about the product than the id. You can use `IapManager.ObtainProductInfo()` to get associated `ProductInfo` for your product string identifiers using a dictionary. This was called transparently previously however like I said we think it is more flexible this way if you want to check more info for the product.

In any case we keep your suggestion in mind and we are looking to improve the API based on your feedback, so don't hesitate to gather other devs to your cause :)
