### ISSUE TITLE
BannerAd Size USER_DEFINED? How to Set?

### ISSUE THREAD

**Issue by pacoelayudante** [EvilMindDevs/hms-unity-plugin#137]
Hola,
I noticed there is a Banner Size named USER_DEFINED, I noticed in plugin itself it is checked, and there is a call for something like "getCurrentDirectionBannerSize". But I cannot find in this end how to set that value.
My issue is I want to set a banner size smaller than default size. I have been told by Huawei to just request the fixed size banner (320x50) and make the container smaller instead of trying to get the Smart Banner size.
I was wondering if setting the user defined size is to change the size of the Banner View Container.
Best Regards

**Comment by sametguzeldev** [comment]
Hello there.
USER_DEFINED is probably an old value. Because if you check this documentation, you can see there is no such value called USER_DEFINED.
About the getCurrentDirectionBannerSize method, you can find detailed explanations in the documentation as well.
It says: "Creates a banner ad size based on the current device orientation and a custom width. If the creation fails, BannerAdSize.INVALID is returned."
Our SDK already has this method to pass width as a parameter and return you a BannerAdSize class.

Documentation link : https://developer.huawei.com/consumer/en/doc/development/HMSCore-References-V5/banneradsize-0000001050066831-V5
