### ISSUE TITLE
Need a way to disable execution of HMSGradleFixer and HMSGradleWorker

### ISSUE THREAD

**Issue by catinjar** [EvilMindDevs/hms-unity-plugin#149]
Hi there,

I have separate configurations for Google Play and App Gallery build and don't want HMSGradleFixer and HMSGradleWorker callbacks to be called for the Google Play build.

Right now I'm solving this by setting static flag and checking it in those callbacks. Downside of this is that I have to touch your plugin's source code which is obviously not good.

Maybe there is some built-in workaround in Unity that lets you to disable some editor callbacks but I couldn't find any info on that.

**Comment by sametguzeldev** [comment]
Hello there.
You can define directives to activate platform-dependent compilation. For example, you define HMS_BUILD and GMS_BUILD then put these directives into the scripts that you want. You can put HMS_BUILD directive to HMSGradleFixer and HMSGradleWorker scripts so that these scripts will only compile if you choose to build your apk for App Gallery.
https://docs.unity3d.com/Manual/PlatformDependentCompilation.html see Platform custom #defines section here.

**Comment by catinjar** [comment]
I tried this approach by calling PreprocessorDefineManager.Set before the build. For some reason HMS_BUILD was defined during game build itself but not during callback execution, I guess. So I ended up with a Huawei build that missed HMS classes.

**Comment by sametguzeldev** [comment]
I could not find anything related to PreprocessorDefineManager.Set in Unity docs. Could you link that method in docs so I can check ?

**Comment by catinjar** [comment]
Oh, sorry. I meant to write PlayerSettings.SetScriptingDefineSymbolsForGroup, not my method set wraps this one.

I call PlayerSettings.SetScriptingDefineSymbolsForGroup from the script before the build.

**Comment by sametguzeldev** [comment]
After calling this PlayerSettings.SetScriptingDefineSymbolsForGroup method, scripts need to recompile. Are you letting Unity do recompile before build ?

**Comment by catinjar** [comment]
I'll try to go with AssetDatabase.Refresh after calling PlayerSettings.SetScriptingDefineSymbolsForGroup, thanks.

I can close this issue at this point, I guess.
