### ISSUE TITLE
No crossplatform support (crashes and build errors on non huawei platforms)

### ISSUE THREAD

**Issue by Last8Exile** [EvilMindDevs/hms-unity-plugin#162]
1) Plugin does not contains any platform checks and calls AndroidJNI on windows and IOS platforms.

2) No way to disable gradle checking tasks which throwing exception:
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':launcher:processReleaseAGCPlugin'.
> ERROR: Failed to verify AGConnect-Config '/client/package_name', expected: 'other platform package name', but was: 'huawei package name'

What i expect:
Have script define symbol (or toggle in settings) to disable (or enable) Plugin. 
If disabled:
* No build pre/post processing. 
* No dependencies. 
* Managed code mostly(or completly) stripped.

**Comment by sametguzeldev** [comment]
Hello there. Thank you for this beautiful issue. We had this in our minds but never really got into it and code it.
Here is my idea of how to improve it.

I agree that we should have a toggle in settings that enables/disables the plugin. If disabled, we strip all code regarding our plugin and make users get an android build without the Gradle error.

For platform-dependent compilation, rather than writing platform-dependent directives, we should just abort the build if the platform is not set to Android and the plugin is enabled. I see no reason to get a build for Windows or iOS platforms when the plugin is enabled. It won't work anyway.

**Comment by sametguzeldev** [comment]
Hello. There are updates about this in #167 .

**Comment by sametguzeldev** [comment]
Fixed in #169
