### ISSUE TITLE
IAP the method ObtainOwnedPurchases() does not return purchased products and subscriptions

### ISSUE THREAD

**Issue by tomas11bala** [EvilMindDevs/hms-unity-plugin#182]

**Comment by sametguzeldev** [comment]
Hello there.
Can you elaborate on this issue? Are you testing this in a test environment or on real app?

**Comment by tomas11bala** [comment]
I test it in a real application via a sandbox. After making a purchase, callbacks OnBuyProductSuccess returns all the correct values to me. But method ObtainOwnedPurchases() return empty list.

**Comment by sametguzeldev** [comment]
ObtainOwnedPurchases will result in empty list on the sandbox environment. Because sandbox purchases are not actual purchases and you can buy over and over again(this also goes for non-consumable products you can consume the same product over and over again).
I haven't tried this tho: Buying the product but not consuming the product and calling ObtainOwnedPurchases. Maybe in that way you can get a list.

But that differs for subscription products. There are time periods for that.
![image](https://user-images.githubusercontent.com/6827857/134184698-dc355108-e9ad-4070-8580-46e39b7441fa.png)

You can find detailed information [here](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/sandbox-testing-0000001050035039)

**Comment by sametguzeldev** [comment]
Closed due to inactivity. Please re-open if the issue still persists.
