### ISSUE TITLE
Impression callback doesn't work for Interstitial and doesn't exist for Rewarded Video

### ISSUE THREAD

**Issue by Whaledevelop** [EvilMindDevs/hms-unity-plugin#254]
Hello!

I am using HMSAdsKitManager, and its InterstitialAdListener.OnAdImpression is never called. Checked for test and release ad ids. Checked for versions 2.0.15 and 2.0.10 of plugin. Method is not called neither after showing, clicking, or closing Interstitial. All other callbacks (OnAdClicked, OnAdClosed, OnAdFailed, OnAdLoaded) work as expected.

In the same time, impression callback is working fine for Banners (AdStatusListener.onAdImpression). I have noticed that java interfaces for InterstitialAd and BannerAd are completely different : `org.m0skit0.android.hms.unity.ads.BannerAd` for BannerAd and `com.huawei.hms.ads.InterstitialAd` for InterstitialAd. Although Huawei Ads Kit has [class for banner](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References-V1/bannerview-0000001050187695-V1). Is it because of that bug? Is it from Huawei Ads Kit?

About Rewarded Video : I assume that getting impression is not provided for Rewarded Video by Huawei Ads Kit because [RewardAdStatusListener](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References-V1/reward-ad-status-lisnr-0000001050289462-V1) doesn't include impression callback. So does IRewardAdStatusListener in your plugin. Am I right? Do you know how to get impression from Rewarded Video?

Thanks a lot!

**Comment by sametguzeldev** [comment]
Hello there.
We wrote our own wrapper that is wrapping the banner ad so that is the reason for package names being different. That is not a bug :)

Afaik, Interstitial Ad doesn't have a callback for an Ad impression. I checked the official repo for the interstitial ad I did not see them overriding the AdImpression callback. You can check it out [here](https://github.com/HMS-Core/hms-ads-demo-java/blob/master/app/src/main/java/com/huawei/hms/ads/sdk/InterstitialActivity.java). Maybe we should also remove that callback so it will not confuse developers.

About the Reward Ad impression; since our plugin is just a wrapper for the HMS java ads kit, we are only supporting the functions of the SDK itself. If the official SDK doesn't have a callback, we will also not have it in our plugin.

**Comment by Whaledevelop** [comment]
Thanks a lot! We contacted the Huawei developers, they confirmed that they do not have this functionality.
