### ISSUE TITLE
IAP isnt working

### ISSUE THREAD

**Issue by chsnkoff** [EvilMindDevs/hms-unity-plugin#281]
Problem occurs when running IAP.
Android Logcat while trying to buy product: 
![image](https://user-images.githubusercontent.com/99077539/153198565-cfaf67aa-d218-4a16-8fe7-64a49882a3b5.png)

Android Logcat when IAP Starts
![image](https://user-images.githubusercontent.com/99077539/153199539-69e72e0f-f5d6-4109-9fb3-4070b865f8f4.png)

Huawei>Kit Settings>IAP:
![image](https://user-images.githubusercontent.com/99077539/153198689-1db49228-d44d-4d4e-8686-361b54ee025a.png)

HMSIAPConstants:
![image](https://user-images.githubusercontent.com/99077539/153198918-483fe795-b692-4aed-a266-f119817de7dc.png)

Products in Huawei Store(Многоразовые = Consumable):
![image](https://user-images.githubusercontent.com/99077539/153199070-ebe5940c-310d-41d4-be6c-7e99fb8b7758.png)

Screenshot from Test:
![image](https://user-images.githubusercontent.com/99077539/153199803-2d917d77-ce50-4d42-868b-7eeac96ebacf.png)

Fingerprint(SHA256) match the one on AGC.

Hope for the support

**Comment by alihan98ersoy** [comment]
Hello, 
Are you using our IAP demo scene? In our scene, we are printing a product list. Can you share your logs? And is there any other IAP solution implemented? Maybe that's why it is giving warning.

Example of my logs:
![resim](https://user-images.githubusercontent.com/39373386/153253601-c0780348-e6bd-4f22-bb9d-4c808c1fb127.png)

**Comment by alihan98ersoy** [comment]
Hello,

The problem seems to be with obtaining the Products and filling the product list. Can you try with our demo scene? If it works, you can refer to it.

Also, I checked [supported devices for IAP: ](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/introduction-0000001050033062#section20817330133210)
![resim](https://user-images.githubusercontent.com/39373386/153405849-0a9001a7-c644-416e-a8c9-057a95f73da6.png)

It seems you can use NOX. But we recommend testing with the Huawei device. If you don't have a device you can use Huawei's [Cloud Debugging](https://developer.huawei.com/consumer/en/agconnect/cloud-adjust/) feature.

**Comment by chsnkoff** [comment]
I also tested my app with huawei phone, same result.

Logs from Demo scene:
![image](https://user-images.githubusercontent.com/99077539/153420642-9b2165b6-d4d9-4633-822c-458bbe5baa3c.png)
![image](https://user-images.githubusercontent.com/99077539/153420875-4ed0af4c-100e-48c7-9643-36913b41ed5c.png)
[logs.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/8041441/logs.txt)

**Comment by chsnkoff** [comment]
I find one more error. I get this when i try to create a new product in Huawei>Kit Settings>IAP:
![image](https://user-images.githubusercontent.com/99077539/153577485-778c8451-964c-4bd2-95ec-408d052fae79.png)
[error.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/8047917/error.txt)

**Comment by alihan98ersoy** [comment]
Hello,
Also, I am getting this Exception error on my unity editor but IAP working. This exception not related. I will fix it. But in your case there is some problem with obtaining products part. You have coins1000 in HMSIAPConstants and in your products page on AGC. But it can not obtain. Are you sure is your app on AGC same with your project? Maybe adding products for different app. Also can you try to redownload agconnect-services.json and replace it?

(Redownload agconnect-services.json from your product management page and click myProject to open your project which connected with your app.)
![Screenshot_1](https://user-images.githubusercontent.com/39373386/153581974-cefdf26b-5236-4b5a-9029-9abb43530728.jpg)

**Comment by chsnkoff** [comment]
This is a apge with products of my app. Reimport agconnect-services.json didnt work :(
![image](https://user-images.githubusercontent.com/99077539/153598152-b1f84ac8-0d92-40da-9926-0fa2605b6fa4.png)
![image (1)](https://user-images.githubusercontent.com/99077539/153598156-301402e3-d8e5-4c90-a4b0-0665f9d4f0f7.png)
![image (2)](https://user-images.githubusercontent.com/99077539/153598158-1ba5254e-5ca6-4b44-95db-21432e94ae27.png)

**Comment by alihan98ersoy** [comment]
Hello, 
I've done many tests to reproduce but couldn't reproduce the same issue. The problem may be on the server-side, could you open a ticket to [Huawei customer service](https://developer.huawei.com/consumer/en/support/feedback/#/)?

**Comment by warboss84** [comment]
Hello @chsnkoff @alihan98ersoy 
I have the same problem exactly. I can't make a purchase and I get the same error. Have you been able to find a solution? 
I use Unity 2020.2.21 and HMS v2.1.2 and Huawei Nova 8

I tried also on your demo project and the error is the same. Also, I talked to Huawei support for a few days, and they could not help me.

<img width="1305" alt="1340007000015731620 20220316211329 00256429674794928611092045675598" src="https://user-images.githubusercontent.com/102288151/159879700-3f30f65a-fdc1-402c-b421-1dadc663a15c.png">

**Comment by alihan98ersoy** [comment]
Hello,

Could you please review the [article](https://medium.com/huawei-developers/quickly-integrate-hms-to-your-game-using-hms-unity-plugin-2-0-part-3-2913740f5630)?

Is everything the same as what you did? I will try to occur the same issue by following the steps in the article.

**Comment by warboss84** [comment]
> Hello,
> 
> Could you please review the [article](https://medium.com/huawei-developers/quickly-integrate-hms-to-your-game-using-hms-unity-plugin-2-0-part-3-2913740f5630)?
> 
> Is everything the same as what you did? I will try to occur the same issue by following the steps in the article.

Hello!

Yes, I did everything as in this article. I even created a new project and tried to set up payments. The problem is still the same.
I have attached the logs.
[log.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/8360618/log.txt)

**Comment by alihan98ersoy** [comment]
Hello,

I tested with an empty project. And it is working on me. Then I realize there is a problem with creating a product list. You can put a space end of the product id. 
![Screenshot_6](https://user-images.githubusercontent.com/39373386/160679236-c242bac4-8451-4108-aecd-6bd10982f95a.jpg)

Can you recreate the product list to confirm the products IDs are the same as the AGC console products ids?

**Comment by warboss84** [comment]
> Can you recreate the product list to confirm the products IDs are the same as the AGC console products ids?

Hello! I checked the product id's twice. It's okay. The cycle does not run. And I don't understand why...

Now I stopped at this point. 

This function returned NULL
<img width="1227" alt="Screenshot 2022-03-30 at 11 45 55" src="https://user-images.githubusercontent.com/102288151/160794389-fe058081-87bb-4379-bd3c-4cd13a1223cc.png">

because productInfoList here is null
<img width="1191" alt="Screenshot 2022-03-30 at 11 45 14" src="https://user-images.githubusercontent.com/102288151/160794517-87e4cfcc-eca2-4a93-b253-824620f1a3ac.png">

because here the list is not filled out. The cycle does not run...
<img width="1708" alt="Screenshot 2022-03-30 at 11 58 11" src="https://user-images.githubusercontent.com/102288151/160794620-30b837e9-016e-4d16-b21a-2236e1f72bc6.png">

**Comment by warboss84** [comment]
> 


> did you create a constant class? IAP uses a constant class to obtain product info then fill ProductInfoList.

Yes, I did.

<img width="1596" alt="Screenshot 2022-03-30 at 12 42 45" src="https://user-images.githubusercontent.com/102288151/160803247-bb10dd38-817e-4729-ac5f-195d240df71a.png">

I send you my script and fresh logs
[log.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/8379328/log.txt)
[PurchaseHuawei.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/8379336/PurchaseHuawei.txt)

**Comment by alihan98ersoy** [comment]
Hello,
I will share my example with you maybe we are missing something.
![Screenshot_7](https://user-images.githubusercontent.com/39373386/160810326-4d2ee045-2cbd-4523-be4c-4378b3e1b78e.jpg)
![Screenshot_8](https://user-images.githubusercontent.com/39373386/160810318-9cb4f9d1-de51-48bf-8bbb-848030ae8ddc.jpg)
[myLogs.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/8379612/myLogs.txt)

In my example cons_test_01 not working and getting same error with yours because as you see in my constant class "cons_test_01 " has blank end of it. So I get same issue with wrong product ID. If everything ok with product ID I will keep investigating.

If this is not work can you share your IAP products with export product from console with me? If you want you can mail me. alihan98ersoy@hotmail.com

**Comment by alihan98ersoy** [comment]
![resim](https://user-images.githubusercontent.com/39373386/160812371-0f19e1ae-b4e9-4345-8467-e4388c3a4d51.png)

In my logs I have 4 consumable product in my constants but can obtain 3 of it because my product ID wrong for one of them. In your logs there are 4 consumable but obtaining 0. According to your logs IAP has trouble with obtaining your products.

**Comment by alihan98ersoy** [comment]
Hello,

Your products are type 3, so it should be nonconsumable can you clear and recreate your constants?
![resim](https://user-images.githubusercontent.com/39373386/160840138-19f15ebb-8040-4e7f-be31-4fb55b22aae4.png)

**Comment by warboss84** [comment]
Problem found! Indeed the product type does not match. In the dashboard I have type 3, but in the application I have type 0. I replaced the type - nonconsumable  for one of the products in UNITY and everything worked.

Now the main question? I entered purchases in the dashboard as consumable and in the UNITY entered as consumable. Where did I make a mistake? I have all the payments - consumable.

**Comment by warboss84** [comment]
Figured it out. The problem is in the localization of the AppGallery panel (Russian). These two words are not translated correctly and mislead me.
<img width="1447" alt="Screenshot 2022-03-30 at 16 26 13" src="https://user-images.githubusercontent.com/102288151/160845760-4c9c8f1d-11bc-43df-b6bd-b3da5eb13543.png">

**Comment by alihan98ersoy** [comment]
Huawei technical team is working on the issue.
