### ISSUE TITLE
Please help me, I can't find the interface for deferred payment.

### ISSUE THREAD

**Issue by SxmGit** [EvilMindDevs/hms-unity-plugin#354]
Please help me, I can't find the interface for deferred payment.

**Comment by alihan98ersoy** [comment]
![resim](https://user-images.githubusercontent.com/39373386/187089650-c56be82e-9a1e-4a69-8aaa-2819328435ad.png)
[InAppPurchaseData](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/json-inapppurchasedata-0000001050986125)

![resim](https://user-images.githubusercontent.com/39373386/187089709-c3dfcb55-28a9-4edf-b022-f1ed83a9629d.png)
[InAppPurchaseDataClassSummary](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/inapppurchasedata-0000001050137635#section16427133311489)

is this what you are looking for? We have this method as a field named **DeferFlag** in **HuaweiMobileServices.IAP.InAppPurchaseData**

**Comment by SxmGit** [comment]
![image](https://user-images.githubusercontent.com/109260005/187107978-5eb0f85a-b6b3-4ce4-a2ca-a2659a7dc5c8.png)
[enablePendingPurchase](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/iapclient-0000001050137587#section19183633182613)
I can't find the method to call the above screenshot, do I need to write a method to call it?

**Comment by alihan98ersoy** [comment]
You can modify [HMSIAPManager](https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/Assets/Huawei/Scripts/IAP/HMSIAPManager.cs#L61) but this is not recommended because of possible conflict problem with new versions.
![resim](https://user-images.githubusercontent.com/39373386/187150367-868fead0-2bcf-49b6-af5d-f11d5d7481f0.png)

or You can create your custom logic in your scene for IAP initialization. But do not forget to disable Initialize onStart box.
![resim](https://user-images.githubusercontent.com/39373386/187151255-01d077ff-ecd6-48ec-bccf-5f5f72ef146b.png)

**Comment by SxmGit** [comment]
thanks , I get

**Comment by alihan98ersoy** [comment]
Thank you for your interest in our project. You may give us a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here: https://discord.io/hmsunityplugin
Thank you and stay tuned!
