### ISSUE TITLE
HMS Ads not working in internal build

### ISSUE THREAD

**Issue by imtiaz791** [EvilMindDevs/hms-unity-plugin#437]
Hi, I am using hms unity plugin for huawei ads, this plugin work fine in gradle build but not working in internal build.
Thanks,

**Comment by alihan98ersoy** [comment]
Hi, it should actually be working. 
* Is build successful or failure? 
* And if the build is successful, would you happen to have a chance to review the logs? There should be the reason in the logs. 
* Also, Which Unity version and plugin version are you using?

**Comment by imtiaz791** [comment]
Yes build successful,
Unity version 2018.4.36f1 LTS and plugin version are v2.3.4 - Unity 2018

**Comment by alihan98ersoy** [comment]
If you don't mind can you check the logs for the problem?

**Comment by alihan98ersoy** [comment]
Hi again, while testing I encountered some problems that I need to solve.
![resim](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/41df2ec9-0add-4339-9c4a-cdd1589f58bf)
[Edit>Preferences]
1. Unity 2018.4.36f1 does not contain an internal SDK, so I had to use the SDK path of another version. (Android Studio's path can also be used) I experienced this problem while setting up the keystore. Have you completed the [keystore](https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start/register-your-app-at-huawei-developer#generate-a-keystore) step?
2. The installed Gradle version is 5.1.1, but minimum 5.4.1 is required. I had to download it and change the Gradle path.
3. Reminder: You need to activate the Ads kit from Kit Settings without building.
![resim](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/acbd7755-0811-4f90-8c10-1afe953b0d95)

4. Then I received a license error while building. If you experience the same problem, you can look for the solution [here](https://github.com/EvilMindDevs/hms-unity-plugin/issues/367).

**Comment by imtiaz791** [comment]
![Screenshot_20230927-162919](https://github.com/EvilMindDevs/hms-unity-plugin/assets/52918562/9699645e-db34-488d-83cd-85d879431a76)

**Comment by alihan98ersoy** [comment]
Are you testing with a real device? 
And is minify settings are none? 
![resim](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/ab4d4a5b-82d0-47b3-a5d3-c8fe01e91026)

**Comment by imtiaz791** [comment]
Yes testing on real device.
Minify option hide when internal build.
Thanks,

**Comment by alihan98ersoy** [comment]
The problem seems to be caused by the required library not being downloaded via Gradle and not being included in the game when building. I'm not sure exactly where the problem is, but I'll explain the process step by step and maybe we can find it.

![resim](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/af5bfa5d-4c72-4dd4-bc3f-2a2db5ec7a0e)
* First, we enable Ads Kit from HMS Kit settings. This process performs the necessary operations in the build.gradle file while getting the build. (You can check with the export project) 
![resim](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/7d65e9a3-3bcc-4a1a-bf4c-b7f483c484a7)

But sometimes this action blocking by proguard or different configurations. That's why I suspected Minify, wondering if it was blocking it. 
I think some 3rd party libraries disable gradle and install libraries with features such as (jar-resolver). If you are using such a structure, you may need to make manual changes. You can refer to the official documentation for [Gradle plugin earlier than 7.0](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/publisher-service-integrating-sdk-0000001050066913#EN-US_TOPIC_0000001057762906__li18997105875019).
