### ISSUE TITLE
How to make build on Harmony OS ?

### ISSUE THREAD

**Issue by zeeshan0022** [EvilMindDevs/hms-unity-plugin#478]
Im using this Tuanjie Editor to make Harmony Os build But this plugin not supporting on Harmony build How to use it on Tuanjie Editor

**Comment by zeeshan0022** [comment]
So This plugin not support Harmony build

**Comment by Andronovo-bit** [comment]
Can you share the platform's screenshot, like I can do above?

**Comment by zeeshan0022** [comment]
![Screenshot 2024-03-25 145732](https://github.com/EvilMindDevs/hms-unity-plugin/assets/42519518/1272face-8cc3-485c-8cc1-8363827b6847)

**Comment by zeeshan0022** [comment]
its OpenHarmony .. Its unity China version for building harmony OS build  .. i got it access very difficult

**Comment by Andronovo-bit** [comment]
I see, we don't support this platform right now. But we will put it on our roadmap. Thanks for bringing it to our notice.

**Comment by zeeshan0022** [comment]
Thank u sir. I hope this feature available soon also

**Comment by BA489** [comment]
> I see, we don't support this platform right now. But we will put it on our roadmap. Thanks for bringing it to our notice.

HarmonyOS NEXT don't support HMS anymore because they are base APIs not upper level APIs on an existing platform like Android. So I hope HarmonyOS NEXT is in the global roadmap of Huawei alongside OpenHarmony, to be specific Eclipse Oniro OS project for global/western markets soon after Q4 2024 China launch.
