### ISSUE TITLE
LogOut when change scene

### ISSUE THREAD

**Issue by Guddeisr** [EvilMindDevs/hms-unity-plugin#82]
Hi! I've got a problem for a while. The thing is when I log in on my game on the principal menu and play the game, when I go back to the principal menu I'm no longer logged in.
Other thing that happens is, when I log in I can log in again and again with no problem. Plus, the log out button doesn't work.

My theory is that I'm logging in but it does not stay logged, just changes de message that says "You're logged in".

How can I be sure that I'm logged in the whole time that I'm in the game?

**Comment by sametguzeldev** [comment]
Hello there. This is because when you change your scene, all managers are getting destroyed. We are currently updating the plugin which solves this issue. But if you want to solve it now, be sure to use DontDestroyOnLoad method on manager scripts. But you still need to be careful about opening the same scene. Because then you will have "two" of the same managers. I suggest you to use a Singleton approach on this.
You can find further info about DontDestroyOnLoad from here: https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html
And an article about Singleton in Unity : https://blog.mzikmund.com/2019/01/a-modern-singleton-in-unity/

**Comment by sametguzeldev** [comment]
This behavior has been solved in newer versions.
